export default [
  {
    key: 'burndownchart',
    title: '燃尽图',
    des: '跟踪记录所有问题的剩余工作工作时间，这有助于在团队管理方面取得更进一步的掌控与把握。',
    link: '/agile/reporthost/burndownchart',
    pic: 'burndownchart',
  },
  {
    key: 'sprint',
    title: '冲刺报告图',
    des: '了解每个冲刺中完成、进行和退回待办的工作。这有助于您确定团队的工作量是否超额。',
    link: '/agile/reporthost/sprintReport',
    pic: 'sprint',
  },
  {
    key: 'accumulation',
    title: '累积流量图',
    des: '显示状态的问题，这有助于您识别潜在的瓶颈， 需要对此进行调查。',
    link: '/agile/reporthost/accumulation',
    pic: 'accumulation',
  },
  {
    key: 'versionReport',
    title: '版本报告图',
    des: '跟踪对应的版本发布日期，这有助于您监控此版本是否按时发布，以便工作滞后时能采取行动。',
    link: '/agile/reporthost/versionReport',
    pic: 'versionReport',
  },
  {
    key: 'velocityChart',
    title: '迭代速度图',
    des: '跟踪各个迭代已完成的工时量。这有助于您确定团队的开发速度并预估在未来迭代中能完成的工作量。',
    link: '/agile/reporthost/velocityChart',
    pic: 'velocityChart',
  },
  {
    key: 'epicReport',
    title: '史诗报告图',
    des: '随时了解一个史诗的完成进度。这有助于您跟踪未完成或未分配问题来管理团队的开发进度。',
    link: '/agile/reporthost/EpicReport',
    pic: 'epicReport',
  },
  {
    key: 'pieReport',
    title: '统计图',
    des: '根据指定字段以统计图呈现项目或筛选器下的问题。这可以使您一目了然地了解问题详情。',
    link: '/agile/reporthost/pieReport',
    pic: 'pieReport',
  },
  {
    key: 'epicBurndown',
    title: '史诗燃耗图',
    des: '跟踪史诗完成速度预计所需冲刺数。这有助于您监控史诗能否按时发布，以便在工作落后时采取行动。',
    link: '/agile/reporthost/epicBurndown',
    pic: 'epicBurndown',
  },
  {
    key: 'versionBurndown',
    title: '版本燃耗图',
    des: '跟踪版本完成速度预计发布日期。这有助于您监控版本能否按时发布，以便在工作落后时采取行动。',
    link: '/agile/reporthost/versionBurndown',
    pic: 'versionBurndown',
  },
];
